apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
    spec:
      containers:
        - name: worker-container
          image: dockersamples/examplevotingapp_worker
          ports:
          - containerPort: 80