apiVersion: v1
kind: Service
metadata:
  name: vote-svc
  labels:
    name: vote-service
spec:
  selector:
    name: vote-app-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30112
  type: NodePort