apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-depl.yaml
  - postgres-svc.yaml

secretGenerator:
- name: postgres-secret
  literals:
  - postgres-username=username123
  - postgres-password=password123
  - postgres-host-auth-method=trust

commonLabels:
  category: database-postgres
  